name: Elixir CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    name: Build and test
    runs-on: ubuntu-latest

    container:
      image: elixir:1.9.1-slim
      env:
        MIX_ENV: test

    services:
      postgres:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Elixir
      uses: actions/setup-elixir@v1
      with:
        elixir-version: 1.11.2 # Define the elixir version [required]
        otp-version: 23.1.2 # Define the OTP version [required]

    - name: Install dependencies
      run: mix deps.get

    - name: Build
      run: mix compile

    - name: Run lint
      run: mix credo

    - name: Run Tests
      run: mix test
      env:
        DB_HOST: postgres
