name: Elixir CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    name: Build and test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Elixir
      uses: actions/setup-elixir@v1
      with:
        elixir-version: 1.11.2 # Define the elixir version [required]
        otp-version: 23.1.2 # Define the OTP version [required]

    - name: Install dependencies
      run: mix deps.get

    - name: Build
      run: mix compile

    - name: Run lint
      run: mix credo
